# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/improved-octo-garbanzo',
                'doc_host': 'https://vilmaguila.github.io',
                'git_url': 'https://github.com/vilmaguila/improved-octo-garbanzo',
                'lib_path': 'improved_octo_garbanzo'},
  'syms': {'improved_octo_garbanzo.core': {'improved_octo_garbanzo.core.foo': ('core.html#foo', 'improved_octo_garbanzo/core.py')}}}
